# Generated by Django 5.2.8 on 2026-03-04 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_category_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_text',
            field=models.TextField(blank=True, help_text='About section text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_text',
            field=models.TextField(blank=True, help_text='Hero section text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='maintainer_name',
            field=models.CharField(default='Jean Marie', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='maintainer_url',
            field=models.URLField(default='https://okalmjohn.netlify.app'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_address',
            field=models.CharField(default='Mama Ngina University', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='UniMart', max_length=100),
        ),
        migrations.CreateModel(
            name='SomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
